server:
  port: ${INVENTORY_SERVICE_PORT:5007}
  forward-headers-strategy: framework
spring:
  application:
    name: inventory-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
logging:
  level:
    com.gsvn.inventoryservice.queue: INFO
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  use-management-port: false
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.gsvn.inventoryservice.model.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000ms
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      auth-service:
        base-config: default
      hrm-service:
        base-config: default
      shipment-service:
        base-config: default
      rabbitmq-publisher:
        base-config: default