
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB: MYSQL
      DB_URL_HOST: mysql
      DB_SCHEMA: keycloak
      DB_USERNAME: keycloak
      DB_PASSWORD: keycloak
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - mysql-db
    command:
      - "start-dev"
  mysql-db:
    container_name: gmvn_db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: gmvn
        MYSQL_USER: higan
        MYSQL_PASSWORD: passpass
        MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d #scripts sql docker
    expose:
      - 3307
volumes:
  mysql_data:
    driver: local