server:
  port: 5005

spring:
  security:
    user:
      name:
      password:

  datasource:
    url: "jdbc:sqlite:"
    driverClassName: "org.sqlite.JDBC"
    username:
    password:
    hikari:
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

  cloud:
    consul:
      host:
      port:
      discovery:
        service-name: address-service
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: false
        heartbeat:
          enabled: true
          ttl: 300s
        health-check-critical-timeout: 12m
mybatis:
  configuration:
    map-underscore-to-camel-case: true