version: '3.8'
services:
  eureka:
    build:
      context: ../EurekaServer
      dockerfile: Dockerfile
    container_name: ${EUREKA_CONTAINER_NAME}
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    env_file:
      - .env
    environment:
      - SERVER_PORT=${EUREKA_PORT}
      - SPRING_SECURITY_USER_NAME=${EUREKA_USER}
      - SPRING_SECURITY_USER_PASSWORD=${EUREKA_PASSWORD}
    networks:
      - gsvn_network
networks:
  gsvn_network:
    driver: bridge