server:
  port: 5001

spring:

  security:
    user:
      name: abc1234
      password: abc1234
  datasource:
    url: "jdbc:postgresql://postgres:5432/gsvn_dev?currentSchema=acc_db"
    driverClassName: "org.postgresql.Driver"
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: acc_db
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    consul:
      host:
      port:
      discovery:
        service-name:
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address:
        heartbeat:
          enabled: true
          ttl: 60s
        health-check-critical-timeout: 2m
jwt:
  signerKey: "5661608670d8591f4a9b407b975e1195d5204481358997c4e512803b87944062"
  valid-duration: 3600
  refreshable-duration: 36000
app:
  security:
    internal-api-key: "SECRET KEY"