spring:
  profiles:
    active : proc
  application:
    name: auth-service
server:
  port: 5001
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
