spring:
  security:
    user:
      name: ${NOTIFICATION_SERVICE_USER:abc1234}
      password: ${NOTIFICATION_SERVICE_PASSWORD:abc1234}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      username: default
      password: ${REDIS_PASSWORD:admin1234}
      database: ${NOTIFICATION_REDIS_DATABASE:9}
  cloud:
    consul:
      host: ${CONSUL_HOST:consul-server-1}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: notification-service
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: false
        heartbeat:
          enabled: true
          ttl: 300s
        health-check-critical-timeout: 12m

jwt:
  signerKey: ${JWT_SIGNER_KEY:5661608670d8591f4a9b407b975e1195d5204481358997c4e512803b87944062}

app:
  security:
    internal-api-key: ${INTERNAL_API_KEY:gsvn}