INSERT INTO product.fandoms (fandom_title, created_at, updated_at, version) VALUES
                                                                                ('Call of the Night', NOW(), NOW(), 0),
                                                                                ('Captain Tsubasa', NOW(), NOW(), 0),
                                                                                ('Cardcaptor Sakura Series', NOW(), NOW(), 0),
                                                                                ('Carneades', NOW(), NOW(), 0),
                                                                                ('Cat Planet', NOW(), NOW(), 0),
                                                                                ('Cells at Work!!', NOW(), NOW(), 0),
                                                                                ('Chainsaw Man', NOW(), NOW(), 0),
                                                                                ('Character Vocal Series', NOW(), NOW(), 0);

INSERT INTO product.categories (category_title, category_parent_id, created_at, updated_at, version) VALUES
                                                                                                          ('Nendoroid', 0, NOW(), NOW(), 0),
                                                                                                          ('Scale Figure', 0, NOW(), NOW(), 0),
                                                                                                          ('Figma', 0, NOW(), NOW(), 0),
                                                                                                          ('Anime', 0, NOW(), NOW(), 0),
                                                                                                          ('Manga', 0, NOW(), NOW(), 0),
                                                                                                          ('VTuber', 0, NOW(), NOW(), 0),
                                                                                                          ('Game', 0, NOW(), NOW(), 0);
INSERT INTO product.brands (brand_title, brand_email, created_at, updated_at, version) VALUES
                                                                                           ('Good Smile Company', 'info@goodsmile.jp', NOW(), NOW(), 0),
                                                                                           ('Kotobukiya', 'support@kotobukiya.co.jp', NOW(), NOW(), 0),
                                                                                           ('Max Factory', 'info@maxfactory.jp', NOW(), NOW(), 0),
                                                                                           ('Aniplex', 'support@aniplex.co.jp', NOW(), NOW(), 0),
                                                                                           ('Alter', 'info@alter-web.jp', NOW(), NOW(), 0),
                                                                                           ('Bandai Spirits', 'support@bandaispirits.co.jp', NOW(), NOW(), 0),
                                                                                           ('Union Creative', 'info@union-creative.jp', NOW(), NOW(), 0);

INSERT INTO product.spu (
    spu_title,
    spu_description,
    spu_type,
    start_order,
    end_order,
    category_id,
    fandom_id,
    brand_id,
    status,
    sort,
    is_deleted,
    spu_attrs,
    created_at,
    updated_at
) VALUES
      ('Nendoroid Hatsune Miku V4',
       'A Nendoroid of Hatsune Miku V4! Comes with three face plates and microphone.',
       'FIGURE',
       '2024-01-15',
       '2024-03-15',
       1,  -- Nendoroid
       8,  -- Character Vocal Series
       1,  -- Good Smile Company
       'InStock',
       1,
       false,
       '{"Type": 1}',
       NOW(),
       NOW()),
      ('figma Link: Tears of the Kingdom ver.',
       'From "The Legend of Zelda: Tears of the Kingdom", Link joins the figma series!',
       'FIGURE',
       '2024-02-20',
       '2024-04-20',
       3,  -- Figma
       1,
       1,  -- Good Smile Company
       'PreOrder',
       2,
       false,
       '{"Type": 1}',
       NOW(),
       NOW()),
      ('Scale Figure - Aqua: Bunny Ver.',
       'Aqua from "KonoSuba" in a bunny outfit! 1/4 scale.',
       'SCALE_FIGURE',
       '2024-03-01',
       '2024-05-31',
       2,  -- Scale Figure
       1,
       1,  -- Good Smile Company
       'InStock',
       3,
       false,
       '{"Type": 1}',
       NOW(),
       NOW()),
      ('Nendoroid - Tanjiro Kamado',
       'Tanjiro Kamado from Demon Slayer: Kimetsu no Yaiba!',
       'FIGURE',
       '2024-05-01',
       '2024-07-01',
       1,
       7,
       1,
       'InStock',
       4,
       false,
       '{"Type": 1}',
       NOW(),
       NOW()),
      ('figma - Samus Aran: Metroid Dread ver.',
       'Samus Aran from Metroid Dread is now a figma!',
       'FIGURE',
       '2024-06-10',
       '2024-08-10',
       3,
       1,
       1,
       'PreOrder',
       5,
       false,
       '{"Type": 1}',
       NOW(),
       NOW()),
      ('Scale Figure - Rem: Birthday Lingerie ver.',
       'Rem in a special birthday lingerie outfit. 1/7 scale figure.',
       'SCALE_FIGURE',
       '2024-07-15',
       '2024-09-15',
       2,
       1,
       2,
       'InStock',
       6,
       false,
       '{"Type": 1}',
       NOW(),
       NOW()),
      ('Nendoroid - Kirby: Adventure',
       'Kirby from Kirby: Adventure! Comes with cute accessories.',
       'FIGURE',
       '2024-08-01',
       '2024-10-01',
       1,
       1,
       1,
       'InStock',
       7,
       false,
       '{"Type": 1}',
       NOW(),
       NOW()),
      ('figma - Guts: Berserk Armor ver. Repaint Edition',
       'Guts in his Berserk Armor from Berserk.',
       'FIGURE',
       '2024-09-20',
       '2024-11-20',
       3,
       1,
       3,
       'PreOrder',
       8,
       false,
       '{"Type": 1}',
       NOW(),
       NOW()),
      ('Scale Figure - Asuna: Undine ver.',
       'Asuna in her Undine outfit from Sword Art Online.',
       'SCALE_FIGURE',
       '2024-10-01',
       '2024-12-31',
       2,
       1,
       4,
       'InStock',
       9,
       false,
       '{"Type": 1}',
       NOW(),
       NOW()),
      ('Nendoroid - Eren Yeager',
       'Eren Yeager from Attack on Titan.',
       'FIGURE',
       '2024-11-15',
       '2025-01-15',
       1,
       1,
       1,
       'InStock',
       10,
       false,
       '{"Type": 1}',
       NOW(),
       NOW());
INSERT INTO product.spu_sku (spu_id, sku_id, is_deleted, created_at, updated_at) VALUES
                                                                                     (1, 1, false, NOW(), NOW()),
                                                                                     (1, 2, false, NOW(), NOW()),
                                                                                     (2, 3, false, NOW(), NOW()),
                                                                                     (3, 4, false, NOW(), NOW()),
                                                                                     (4, 5, false, NOW(), NOW()),
                                                                                     (5, 6, false, NOW(), NOW()),
                                                                                     (6, 7, false, NOW(), NOW()),
                                                                                     (7, 8, false, NOW(), NOW()),
                                                                                     (7, 9, false, NOW(), NOW()),
                                                                                     (9, 10, false, NOW(), NOW())
                                                                                        ;


INSERT INTO product.sku (
    sku_no,
    sku_title,
    category_id,
    fandom_id,
    brand_id,
    sku_attrs,
    sku_type,
    start_order,
    end_order,
    sku_stock,
    sku_price,
    status
) VALUES
      ('GSC-NEN-12345', 'Nendoroid Hatsune Miku V4', 1, 8, 1, '{"Type": 1}', 'Available', '2024-01-15', '2024-03-15', 100, 50.00, 'InStock'),
      ('MAX-FIG-67890', 'figma Link: Tears of the Kingdom ver.', 3, 1, 3, '{"Type": 1}', 'PreOrder', '2024-02-20', '2024-04-20', 0, 80.00, 'OutOfStock'),
      ('KOTO-SCALE-24680', 'Scale Figure - Aqua: Bunny Ver.', 2, 1, 2, '{"Type": 1}', 'Available', '2024-03-01', '2024-05-31', 50, 120.00, 'InStock'),
      ('GSC-NEN-98765', 'Nendoroid Tanjiro Kamado', 1, 7, 1, '{"Type": 1}', 'Available', '2024-05-01', '2024-07-01', 120, 60.00, 'InStock'),
      ('MAX-FIG-54321', 'figma - Samus Aran: Metroid Dread ver.', 3, 1, 3, '{"Type": 1}', 'PreOrder', '2024-06-10', '2024-08-10', 0, 90.00, 'OutOfStock'),
      ('ANIPLEX-SCALE-13579', 'Scale Figure - Rem: Birthday Lingerie ver.', 2, 1, 4, '{"Type": 1}', 'Available', '2024-07-15', '2024-09-15', 30, 150.00, 'InStock'),
      ('GSC-NEN-24681', 'Nendoroid - Kirby: Adventure', 1, 1, 1, '{"Type": 1}', 'Available', '2024-08-01', '2024-10-01', 80, 45.00, 'InStock'),
      ('MAX-FIG-86420', 'figma - Guts: Berserk Armor ver. Repaint Edition', 3, 1, 3, '{"Type": 1}', 'PreOrder', '2024-09-20', '2024-11-20', 0, 100.00, 'OutOfStock'),
      ('ALTER-SCALE-97531', 'Scale Figure - Asuna: Undine ver.', 2, 1, 5, '{"Type": 1}', 'Available', '2024-10-01', '2024-12-31', 20, 140.00, 'InStock'),
      ('GSC-NEN-13579', 'Nendoroid - Eren Yeager', 1, 1, 1,  '{"Type": 1}','Available', '2024-11-15', '2025-01-15', 90, 55.00, 'InStock');


INSERT INTO product.sku_attr (sku_id, attr_name, attr_value) VALUE (1, 'Type', '1');
