spring:
  security:
    user:
      name: ${ORDER_SERVICE_USER:abc1234}
      password: ${ORDER_SERVICE_PASSWORD:abc1234}
  
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:gsvn_dev}?currentSchema=${ORDER_DB_SCHEMA:order_db}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      pool-name: order-service-gsvn-pool

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
        acknowledge-mode: auto

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      username: default
      password: ${REDIS_PASSWORD:admin1234}
      database: ${ORDER_REDIS_DATABASE:7}

  cloud:
    consul:
      host: ${CONSUL_HOST:consul-server-1}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: order-service
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: false
        heartbeat:
          enabled: true
          ttl: 60s
        health-check-critical-timeout: 2m

jwt:
  signerKey: ${JWT_SIGNER_KEY:5661608670d8591f4a9b407b975e1195d5204481358997c4e512803b87944062}

app:
  security:
    internal-api-key: ${INTERNAL_API_KEY:gsvn}
  order-time-out: ${ORDER_TIMEOUT:15}