server:
  port: ${ORDER_SERVICE_PORT:5013}

spring:
  application:
    name: order-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.gsvn.orderservice.model.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

logging:
  level:
    com.gsvn.orderservice: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always