
spring:

  security:
    user:
      name: abc1234
      password: abc1234
eureka:
  client:
    service-url:
      defaultZone: http://abc1234:abc1234@eureka:8761/eureka/
app:
  security:
    internal-api-key: "key"