

spring:
  security:
    user:
      name: abc1234
      password: abc1234
  datasource:
    url: "jdbc:postgresql://postgres:5432/gsvn_dev?currentSchema=cart_db"
    driverClassName: "org.postgresql.Driver"
    username: postgres
    password: postgres
  cloud:
    consul:
      host:
      port:
      discovery:
        service-name:
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: false
        heartbeat:
          enabled: true
          ttl: 60s
        health-check-critical-timeout: 2m
