spring:
  security:
    user:
      name: ${MEDIA_SERVICE_USER:abc1234}
      password: ${MEDIA_SERVICE_PASSWORD:abc1234}
  cloud:
    consul:
      host: ${CONSUL_HOST:consul-server-1}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: media-service
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: false
        heartbeat:
          enabled: true
          ttl: 300s
        health-check-critical-timeout: 12m
jwt:
  signerKey: ${JWT_SIGNER_KEY:5661608670d8591f4a9b407b975e1195d5204481358997c4e512803b87944062}
s3:
  endpoint: ${S3_ENDPOINT:http://minio:9000}
  region: ${S3_REGION}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  external-url: ${S3_EXTERNAL_URL:http://localhost:9000}
  bucket-name: ${S3_BUCKET_NAME}
  temp-bucket-name: ${S3_TEMP_BUCKET_NAME}